### ISSUE TITLE
flask server CORS 문제 (프런트에서 백엔드 리소스 사용하기 위해)

### ISSUE THREAD

**Issue by ArtemisDicoTiar** [eubinecto/youtora#85]
#### CORS란
> Cross-Origin Resource Sharing(CORS)은 추가적인 HTTP header를 사용해서 애플리케이션이 다른 origin의 리소스에 접근할 수 있도록 하는 메커니즘을 말합니다. 하지만 다른 origin에서 내 리소스에 함부로 접근하지 못하게 하기 위해 사용된다.

#### CORS는 왜 필요한가요?
> 만약 내가 서비스하고 있지 않은 사이트에서 세션을 요청해서 세션을 획득할 수 있다면 해당 사이트는 악의적으로 내 세션을 탈취하거나 다른 행동을 할 수 있습니다. 그래서 브라우저에서는 이러한 요청을 막습니다. 피싱사이트가 대표적인 공격 사례인데 이러한 것을 막고 내가 허용한 origin들만 요청할 수 있도록 하기 위해 필요합니다.

#### CORS는 어떻게 동작하나요?
> 브라우저가 리소스를 요청할 때 추가적인 헤더에 정보를 담습니다. 내 origin은 무엇이고 어떤 메소드를 사용해서 요청을 할 것이고 어떤 헤더들을 포함할 것인지를 담아서 서버에 전송합니다. 서버는 서버가 응답할 수 있는 origin들을 헤더에 담아서 브라우저에게 보냅니다. 브라우저가 이 헤더를 보고 해당 origin에서 요청할 수 있다면 리소스 전송을 허용하고 만약 불가능하다면 에러를 발생시킵니다.

#### 해결방법
https://pypi.org/project/Flask-Cors/1.10.3/#:~:text=In%20the%20simplest%20case%2C%20initialize,cross%2Dorigin%2Dworld!%22
~~~bash
$ pip install -U flask-cors
~~~

~~~python
# EXAMPLE
app = Flask(__name__)
cors = CORS(app)

@app.route("/")
def helloWorld():
  return "Hello, cross-origin-world!"
~~~

~~~python
# EXPECTED SOLUTION
from flask import Flask
from flask_cors import CORS
...
# solution1 : 이러면 모든 리소스에 대해 풀림
cors = CORS(app)

# solution2: 이러면 모든 요청 호스트가 /api/*로의 요청이 풀림
cors = CORS(app, resources={r"/api/*": {"origins": "*"}})

# solution3: decorator 활용 (이러면 특정 함수에 대해서만 풀림.)
@app.route("/")
@cross_origin()
def helloWorld():
  return "Hello, cross-origin-world!"
...
~~~

**Comment by eubinecto** [comment]
@ArtemisDicoTiar 
수정하고 서버로직도 업데이트를 하였음! 문제가 해결되었는지 프론트에서 확인바람.

**Comment by ArtemisDicoTiar** [comment]
@eubinecto flask 서버 재시작 하셨나유?

**Comment by eubinecto** [comment]
@ArtemisDicoTiar 
서버 가상환경 업데이트를 안했구먼유. 업데이트하고 재시작함. 다시 확인 바람!
