### ISSUE TITLE
유튜브 플레이 언어 설정 방법 모색 (자동 번역의 경우 설정 불가)

### ISSUE THREAD

**Issue by ArtemisDicoTiar** [eubinecto/youtora#96]

**Comment by eubinecto** [comment]
자막의 타입도
- manual
- auto
로 포함해서, api에서 보여주면 도움이 될까?

manual 이면 자막 언어 설정을 하고, auto면 불가능 하니 그냥 자막을 꺼두는 방향으로.

**Comment by ArtemisDicoTiar** [comment]
이거 embed파라미터로 분명 설정하는 방법이 있을 거 같은데 찾아봐야됨.
https://developers.google.com/youtube/player_parameters#:~:text=and%20search%20results.-,Embed%20a%20player%20using%20an%20tag,the%20dimensions%20of%20the%20player.

**Comment by ArtemisDicoTiar** [comment]
일단 합법적인 파라미터로는 불가능한 것으로 확인됨.
